export const ERROR_CODE = {
  ERR_NETWORK: 'ERR_NETWORK',
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER_ERROR: 500,
  FORBIDDEN: 403,
  UNPROCESSABLE_ENTITY: 422,
  NOT_FOUND: 'NotFound',
};
